name: CI-Build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Build
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
        # checkout the repository
        - name: Checkout 
          uses: actions/checkout@v2
          with:
             persist-credentials: false

        # do a make clean
        - name: make clean
          run: make clean
